### ISSUE TITLE
Nick is black when displayed in an action (e.g. /me name is black)

### ISSUE THREAD

**Issue by pmclanahan** [zvuc/Aquamarine#6]
This isn't really a big deal, but it does make the line look odd. 

![screenshot 2015-02-25 11 24 30](https://cloud.githubusercontent.com/assets/19934/6374762/ffcb9dae-bce0-11e4-933e-bbc814964a19.png)

There was some discussion of the exact issue in #themes on irccloud's network yesterday:

> 13:18 &lt;Anzrael&gt; So the solution I've found is to change the specificity on the nick style for the theme
> 13:18 &lt;Anzrael&gt; https://www.irccloud.com/pastebin/xzenzPss
> 13:20 &lt;Anzrael&gt; its because the IRCCloud site style has a definition for div.log div.row span a.author now and it gives it the color of #222.

You said you'd remember, but I thought this would be more convenient. Thanks again for an excellent theme!

**Comment by Anzrael** [comment]
I actually did a pull request and fixed this issue (which zvuc opened as #3)! If you go to https://userstyles.org/styles/104692/irccloud-aquamarine-theme and update your theme, you should be good to go :)

**Comment by zvuc** [comment]
Yup, it is fixed, thanks again @Anzrael :)
